import type { Customer, Lead, Quote, Order, Payment, Expense, Supplier } from './types'

export const demoCustomers: Omit<Customer, 'created_at' | 'updated_at'>[] = [
  {
    id: 'c1',
    full_name: 'שרה כהן',
    phone: '052-1234567',
    instagram: '@sarah_cohen',
    email: 'sarah@example.com',
    city: 'תל אביב',
    source: 'אינסטגרם',
    customer_status: 'VIP',
    notes: 'לקוחה קבועה, אוהבת יהלומים עגולים',
  },
  {
    id: 'c2',
    full_name: 'מיכל לוי',
    phone: '054-9876543',
    instagram: '@michal_levi',
    email: 'michal@example.com',
    city: 'רמת גן',
    source: 'המלצה',
    customer_status: 'פעיל',
    notes: '',
  },
  {
    id: 'c3',
    full_name: 'רחל ברק',
    phone: '050-5556666',
    email: 'rachel@example.com',
    city: 'הרצליה',
    source: 'אתר',
    customer_status: 'חדש',
    notes: 'עניין בטבעת אירוסין',
  },
  {
    id: 'c4',
    full_name: 'דנה מזרחי',
    phone: '053-7778888',
    instagram: '@dana_miz',
    city: 'ירושלים',
    source: 'פייסבוק',
    customer_status: 'פעיל',
    notes: '',
  },
  {
    id: 'c5',
    full_name: 'אורית שפירא',
    phone: '058-2223333',
    email: 'orit@example.com',
    city: 'חיפה',
    source: 'המלצה',
    customer_status: 'לא פעיל',
    notes: 'ביצעה הזמנה לפני שנה',
  },
]

export const demoSuppliers: Omit<Supplier, 'created_at'>[] = [
  {
    id: 's1',
    name: 'יהלומי הצפון',
    contact_name: 'יוסי גולדברג',
    phone: '03-5551234',
    category: 'יהלומים',
    location: 'רמת גן, בורסת היהלומים',
    delivery_time: '3-5 ימי עסקים',
    quality_rating: 5,
    reliability_rating: 5,
    price_rating: 3,
    notes: 'ספק ראשי ליהלומים מעוגלים',
  },
  {
    id: 's2',
    name: 'זהב ישראל',
    contact_name: 'אברהם כץ',
    phone: '03-7654321',
    category: 'זהב',
    location: 'בני ברק',
    delivery_time: '1-2 ימי עסקים',
    quality_rating: 4,
    reliability_rating: 5,
    price_rating: 4,
    notes: 'זהב 14K ו-18K',
  },
  {
    id: 's3',
    name: 'אומן תכשיטים',
    contact_name: 'חיים רוזנברג',
    phone: '02-1234567',
    category: 'ייצור',
    location: 'ירושלים',
    delivery_time: '7-14 ימי עסקים',
    quality_rating: 5,
    reliability_rating: 4,
    price_rating: 3,
    notes: 'עבודת יד פרמיום',
  },
]

export const demoLeads: Omit<Lead, 'created_at' | 'updated_at'>[] = [
  {
    id: 'l1',
    customer_id: 'c3',
    full_name: 'רחל ברק',
    phone: '050-5556666',
    source: 'אתר',
    jewelry_type: 'טבעת אירוסין',
    diamond_type: 'עגול',
    gold_type: '18K',
    budget: 15000,
    lead_status: 'בטיפול',
    priority: 'גבוה',
    follow_up_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'מחפשת טבעת עם יהלום 1 קראט',
  },
  {
    id: 'l2',
    full_name: 'נועה גרינברג',
    phone: '052-4445555',
    source: 'אינסטגרם',
    jewelry_type: 'עגילים',
    diamond_type: 'מרקיז',
    gold_type: '14K',
    budget: 5000,
    lead_status: 'חדש',
    priority: 'בינוני',
    follow_up_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: '',
  },
  {
    id: 'l3',
    full_name: 'יעל כהן',
    phone: '054-6667777',
    source: 'המלצה',
    jewelry_type: 'צמיד',
    gold_type: '18K',
    budget: 8000,
    lead_status: 'ממתין',
    priority: 'נמוך',
    notes: 'ממתינה להצעת מחיר',
  },
  {
    id: 'l4',
    customer_id: 'c4',
    full_name: 'דנה מזרחי',
    phone: '053-7778888',
    source: 'פייסבוק',
    jewelry_type: 'שרשרת',
    diamond_type: 'עגול',
    gold_type: '14K',
    budget: 6000,
    lead_status: 'הומר',
    priority: 'גבוה',
    notes: 'הומר להצעת מחיר Q2405-312',
  },
]

export const demoQuotes: Omit<Quote, 'created_at' | 'updated_at'>[] = [
  {
    id: 'q1',
    quote_number: 'Q2405-101',
    customer_id: 'c1',
    jewelry_type: 'טבעת אירוסין',
    description: 'טבעת סוליטר עם יהלום עגול 1 קראט זהב 18K לבן',
    diamond_type: 'Round',
    diamond_origin: 'טבעי',
    diamond_certificate: 'GIA',
    gold_type: '18K',
    gold_color: 'לבן',
    carat: 1.0,
    diamond_color: 'F',
    diamond_clarity: 'VS1',
    diamond_cut: 'Excellent',
    diamond_cost: 12000,
    gold_cost: 1500,
    labor_cost: 800,
    setting_cost: 500,
    packaging_cost: 150,
    shipping_cost: 0,
    other_cost: 0,
    total_cost: 14950,
    sale_price: 22000,
    expected_profit: 7050,
    profit_margin: 32.05,
    quote_status: 'אושרה',
    valid_until: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: '',
  },
  {
    id: 'q2',
    quote_number: 'Q2405-102',
    customer_id: 'c2',
    jewelry_type: 'עגילים',
    description: 'עגילי יהלום עגולים 0.5 קראט כל אחד זהב 14K',
    diamond_type: 'Round',
    diamond_origin: 'טבעי',
    diamond_certificate: 'IGI',
    gold_type: '14K',
    gold_color: 'צהוב',
    carat: 0.5,
    diamond_color: 'G',
    diamond_clarity: 'VS2',
    diamond_cut: 'Very Good',
    diamond_cost: 4500,
    gold_cost: 800,
    labor_cost: 400,
    setting_cost: 300,
    packaging_cost: 100,
    shipping_cost: 0,
    other_cost: 0,
    total_cost: 6100,
    sale_price: 9500,
    expected_profit: 3400,
    profit_margin: 35.79,
    quote_status: 'נשלחה',
    valid_until: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'לקוחה ביקשה גם אפשרות בזהב לבן',
  },
  {
    id: 'q3',
    quote_number: 'Q2405-103',
    customer_id: 'c4',
    jewelry_type: 'שרשרת',
    description: 'שרשרת יהלומים 0.3 קראט סה"כ זהב 14K',
    diamond_type: 'Round',
    diamond_origin: 'מעבדה',
    diamond_certificate: 'SGL',
    gold_type: '14K',
    gold_color: 'צהוב',
    carat: 0.3,
    diamond_color: 'H',
    diamond_clarity: 'SI1',
    diamond_cut: 'Good',
    diamond_cost: 2500,
    gold_cost: 600,
    labor_cost: 350,
    setting_cost: 200,
    packaging_cost: 80,
    shipping_cost: 50,
    other_cost: 0,
    total_cost: 3780,
    sale_price: 6000,
    expected_profit: 2220,
    profit_margin: 37.0,
    quote_status: 'טיוטה',
    notes: '',
  },
]

export const demoOrders: Omit<Order, 'created_at' | 'updated_at'>[] = [
  {
    id: 'o1',
    order_number: 'O2405-001',
    customer_id: 'c1',
    quote_id: 'q1',
    jewelry_type: 'טבעת אירוסין',
    description: 'טבעת סוליטר עם יהלום עגול 1 קראט זהב 18K לבן',
    diamond_type: 'עגול',
    gold_type: '18K',
    gold_color: 'לבן',
    size: '7',
    engraving: 'S & D ❤️',
    supplier_id: 's3',
    order_status: 'בייצור',
    production_status: 'הזמנת יהלום',
    sale_price: 22000,
    deposit_amount: 11000,
    balance_due: 11000,
    total_cost: 14950,
    net_profit: 7050,
    profit_margin: 32.05,
    payment_status: 'שולם חלקית',
    delivery_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'אירוסין ב-10 ביוני - חשוב!',
  },
  {
    id: 'o2',
    order_number: 'O2405-002',
    customer_id: 'c2',
    jewelry_type: 'עגילים',
    description: 'עגילי יהלום עגולים 0.5 קראט זהב 14K צהוב',
    diamond_type: 'עגול',
    gold_type: '14K',
    gold_color: 'צהוב',
    supplier_id: 's3',
    order_status: 'מוכן',
    production_status: 'הושלם',
    sale_price: 9500,
    deposit_amount: 4750,
    balance_due: 4750,
    total_cost: 6100,
    net_profit: 3400,
    profit_margin: 35.79,
    payment_status: 'שולם חלקית',
    delivery_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: '',
  },
  {
    id: 'o3',
    order_number: 'O2404-015',
    customer_id: 'c5',
    jewelry_type: 'טבעת נישואין',
    description: 'טבעת נישואין זהב 18K צהוב חלקה',
    gold_type: '18K',
    gold_color: 'צהוב',
    size: '6',
    supplier_id: 's2',
    order_status: 'נמסר',
    sale_price: 4500,
    deposit_amount: 4500,
    balance_due: 0,
    total_cost: 2800,
    net_profit: 1700,
    profit_margin: 37.78,
    payment_status: 'שולם במלואו',
    delivery_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'נמסר לשביעות רצון הלקוחה',
  },
]

export const demoPayments: Omit<Payment, 'created_at'>[] = [
  {
    id: 'p1',
    order_id: 'o1',
    customer_id: 'c1',
    payment_type: 'מקדמה',
    payment_method: 'העברה בנקאית',
    amount: 11000,
    payment_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_paid: true,
    notes: 'מקדמה על הזמנת טבעת אירוסין',
  },
  {
    id: 'p2',
    order_id: 'o2',
    customer_id: 'c2',
    payment_type: 'מקדמה',
    payment_method: 'כרטיס אשראי',
    amount: 4750,
    payment_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_paid: true,
    notes: '',
  },
  {
    id: 'p3',
    order_id: 'o3',
    customer_id: 'c5',
    payment_type: 'תשלום מלא',
    payment_method: 'מזומן',
    amount: 4500,
    payment_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_paid: true,
    notes: '',
  },
]

export const demoExpenses: Omit<Expense, 'created_at'>[] = [
  {
    id: 'e1',
    order_id: 'o1',
    supplier_id: 's1',
    expense_type: 'יהלום',
    amount: 12000,
    expense_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_paid: true,
    notes: 'יהלום עגול 1 קראט F VS1',
  },
  {
    id: 'e2',
    order_id: 'o1',
    supplier_id: 's2',
    expense_type: 'זהב',
    amount: 1500,
    expense_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_paid: true,
    notes: 'זהב לבן 18K לטבעת',
  },
  {
    id: 'e3',
    order_id: 'o2',
    supplier_id: 's1',
    expense_type: 'יהלום',
    amount: 4500,
    expense_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_paid: true,
    notes: 'זוג יהלומים עגולים 0.5 קראט',
  },
  {
    id: 'e4',
    supplier_id: 's3',
    expense_type: 'עבודת ייצור',
    amount: 2500,
    expense_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_paid: false,
    notes: 'שכר עבודה אומן לחודש מאי',
  },
]
